spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emaildb?useTimezone=true&serverTimezone=America/Sao_Paulo
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    username: ${DB_USER:thrtec}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 7070
  servlet:
    context-path: /api